# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_bd_cpp <- function(params, max_time, max_species, max_species_extant, min_species, non_extinction, verbose, max_tries, seed, return_tree_size_hist, start_at_crown) {
    .Call(`_ltable_sim_bd_cpp`, params, max_time, max_species, max_species_extant, min_species, non_extinction, verbose, max_tries, seed, return_tree_size_hist, start_at_crown)
}

